server:
  port: 9000

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phone?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true
      poll-interval: 3000ms
      quiet-period: 2999ms
#配置mp
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: state
      logic-delete-value: 0   # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1   # 逻辑未删除值(默认为 0)
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 日志
  type-aliases-package: com.isoft.scenery.pojo.entity   # 别名设置
